name: Deploy Next.js Static to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.20.0'

    - name: Install dependencies
      run: npm ci

    - name: Build and export Next.js
      run: |
        npm run build
        npm run export

    - name: Sync static site to EC2
      uses: appleboy/rsync-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "out/"
        target: ${{ secrets.APP_DIR }}
        flags: "-avz --delete"

    - name: Set permissions
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo chown -R www-data:www-data ${{ secrets.APP_DIR }}
          sudo chmod -R 755 ${{ secrets.APP_DIR }}
