name: Deploy Next.js Static to EC2

# main ブランチに push されたときに実行
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリをチェックアウト
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    # 2. Node.js をセットアップ
    - name: Node.js をセットアップ
      uses: actions/setup-node@v3
      with:
        node-version: '22.20.0'

    # 3. 依存パッケージをインストール（Yarn 使用）
    - name: 依存パッケージをインストール
      run: yarn install --frozen-lockfile

    # 4. Next.js をビルドして静的サイトを生成
    - name: Next.js をビルドして静的サイトを生成
      run: |
        yarn build
        yarn export

    # 5. EC2 にファイルを差分コピー（rsyncで差分更新＆古いファイル削除）
    - name: EC2 にファイルを差分コピー（rsyncで差分更新＆古いファイル削除）
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "out/"
        target: ${{ secrets.APP_DIR }}
        flags: "-avz --delete"

    # 6. EC2 上のファイル権限を Apache 用に設定
    - name: EC2 上のファイル権限を Apache 用に設定
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo chown -R www-data:www-data ${{ secrets.APP_DIR }}
          sudo chmod -R 755 ${{ secrets.APP_DIR }}
