name: Deploy Next.js Static to EC2

# main ブランチに push されたときに実行
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Node.js をセットアップ
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.20.0'

    # 3. 依存パッケージをインストール
    - name: Install dependencies
      run: npm ci

    # 4. Next.js をビルドして静的サイトを生成
    - name: Build and export Next.js
      run: |
        npm run build
        npm run export

    # 5. EC2 にファイルを差分コピー（rsyncで差分更新＆古いファイル削除）
    - name: Sync static site to EC2
      uses: appleboy/rsync-action@v0.1.11
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "out/"
        target: ${{ secrets.APP_DIR }}
        flags: "-avz --delete"

    # 6. EC2 上のファイル権限を Apache 用に設定
    - name: Set permissions
      uses: appleboy/ssh-action@v0.1.11
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo chown -R www-data:www-data ${{ secrets.APP_DIR }}
          sudo chmod -R 755 ${{ secrets.APP_DIR }}
