name: Deploy Next.js Static to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリをチェックアウト
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    # 2. Node.js をセットアップ 
    - name: Node.js をセットアップ
      uses: actions/setup-node@v3
      with:
        node-version: '22.20.0'

    # 3. 依存パッケージをインストール
    - name: 依存パッケージをインストール
      run: yarn install --frozen-lockfile

    # 4. Next.js をビルドして静的サイトを生成
    - name: Next.js をビルドして静的サイトを生成
      run: yarn build

    # 5. rsync を使って EC2 にデプロイ
    - name: rsync で EC2 にデプロイ
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: out/*
        remote_path: ${{ secrets.APP_DIR }}
        remote_host: ${{ secrets.EC2_HOST }}
        remote_user: ${{ secrets.EC2_USER }}
        remote_key: ${{ secrets.EC2_SSH_KEY }}