name: deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      # Node.js をセットアップ
      - name: Node.js をセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: "22.20.0"

      # 依存パッケージをインストール
      - name: 依存パッケージをインストール
        run: yarn install --frozen-lockfile

      # Next.js をビルドして静的サイトを生成
      - name: Next.js をビルドして静的サイトを生成
        run: yarn build

      # 秘密鍵を作成
      - name: 秘密鍵を作成
        run: echo "${{ secrets.EC2_SSH_KEY }}" > key && chmod 600 key

      # rsync でデプロイ
      - name: rsync でデプロイ
        run: |
          rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22" \
          --delete ./out/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.APP_DIR }}/
