name: Deploy Next.js Static to EC2

# main ブランチに push されたときに実行
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリをチェックアウト
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    # 2. Node.js をセットアップ
    - name: Node.js をセットアップ
      uses: actions/setup-node@v3
      with:
        node-version: '22.20.0'

    # 3. 依存パッケージをインストール
    - name: 依存パッケージをインストール
      run: yarn install --frozen-lockfile

    # 4. Next.js をビルドして静的サイトを生成
    - name: Next.js をビルドして静的サイトを生成
      run: yarn build

    # 5. out ディレクトリを tar にまとめる
    - name: out ディレクトリを tar にまとめる
      run: tar -czf out.tar.gz -C out .

    # 6. EC2 に tar ファイルをコピー
    - name: EC2 に tar ファイルをコピー
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "out.tar.gz"
        target: ${{ secrets.APP_DIR }}

    # 7. EC2 上で tar を展開して権限を設定
    - name: EC2 上で tar を展開して権限を設定
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ${{ secrets.APP_DIR }}
          rm -rf ./*              # 古いファイルを削除
          tar -xzf out.tar.gz      # tar を展開
          rm -f out.tar.gz         # tar ファイルを削除
          sudo chown -R apache:apache .
          sudo chmod -R 755 .
